// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// ⚠️ 이 파일은 샘플 파일입니다.
// Firebase 설정을 위해 `flutterfire configure` 명령어를 실행하면
// 이 파일은 자동으로 실제 Firebase 프로젝트 정보로 덮어씌워집니다.
//
// 설정 후 동작 확인:
// 1. Android: google-services.json 파일이 android/app/ 디렉토리에 있는지 확인
// 2. iOS: GoogleService-Info.plist 파일이 ios/Runner/ 디렉토리에 있는지 확인
// 3. 앱을 실행하여 Firebase 초기화가 정상적으로 되는지 확인
//
// 자세한 내용은 FIREBASE_SETUP.md 파일을 참고하세요.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfdt3HXG7GEmjm6oYJfcnEvcPYphVIrzw',
    appId: '1:470445554425:android:2aef2f7f26173dafd3c028',
    messagingSenderId: '470445554425',
    projectId: 'exam-4516e',
    storageBucket: 'exam-4516e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0MEWjej73LTBuAmeUzCtOHj9EP8WQu_A',
    appId: '1:470445554425:ios:ffc1ca750d2dd6b4d3c028',
    messagingSenderId: '470445554425',
    projectId: 'exam-4516e',
    storageBucket: 'exam-4516e.firebasestorage.app',
    androidClientId: '470445554425-o902ft83cbh3s8hnga9l7p854pjvm1st.apps.googleusercontent.com',
    iosClientId: '470445554425-f960jen5h7ndu44999aub25olhi5rt25.apps.googleusercontent.com',
    iosBundleId: 'com.example.blueberryTemplate',
  );
}